name: Build and Push ManageLibrary Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -   name: Checkout code
        uses: actions/checkout@v3

    -  name: Testing project
       run: dotnet test --no-build
        
    -   name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    -   name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_EMAIL}}/apimanagelibrary:${{ github.sha }}, latest
