name: Run Tests and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '7.0'

        - name: Restore dependencies
          run: dotnet restore

        - name: Testing project
          run: dotnet test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    
    -   name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
                
    -   name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: adrianovitordev
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    -   name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
                adrianovitordev/apimanagelibrary:${{ github.sha }}
                adrianovitordev/apimanagelibrary:latest
